project:
  type: website
  output-dir: docs

website:
  description: "A blog built with Quarto"
  site-url: https://lsbjordao.github.io/
  title: "Lucas S.B. Jordão"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lsbjordao/
      - icon: person-vcard
        href: https://lattes.cnpq.br/6445788694639027
  google-analytics: "G-3H8K0NTQRL"

format:
  html:
    theme: cyborg
    css: styles.css



